theme: jekyll-theme-merlot
url: JayDob3.github.io
title: Welcome to Janera Dobson's homepage !
description: Feel free to bookmark this page, for it is my ePotfolio completed within my CS-499-T5477 Computer Science Capstone !
