theme: jekyll-theme-merlot
url: JayDob3.github.io
title: Welcome to Janera Dobson's homepage !
description: Feel free to bookmark this page to keep an eye on my project updates for my CS-499-T5477 Computer Science Capstone !

